# Generated by Django 3.0.10 on 2020-10-05 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHead',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_pagehead', serialize=False, to='cms.CMSPlugin')),
                ('social_panel', models.BooleanField(default=False, verbose_name='Social panel')),
                ('breadcrumbs', models.BooleanField(default=False, verbose_name='Breadcrumbs')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_head_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
