# Generated by Django 3.0.10 on 2020-11-15 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('plugins', '0002_pagehead'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestBlog',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_latestblog', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('posts_number', models.PositiveIntegerField(default=3, verbose_name='Number of posts')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
