# Generated by Django 3.0.10 on 2020-09-28 02:41

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Category name')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Blog categories',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='', max_length=255, verbose_name='Headline')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Creation date')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='Last updated on')),
                ('publication_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='The blog post will be published automatically once a publication date is specified', verbose_name='Publication date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(help_text='Please select one or more categories for this post', related_name='blog_post', to='blog.BlogCategory')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post_image', to=settings.FILER_IMAGE_MODEL)),
                ('post_content', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='post_content', to='cms.Placeholder')),
            ],
            options={
                'verbose_name_plural': 'Blog posts',
                'ordering': ('-publication_datetime',),
            },
        ),
    ]
